export  const allItems = [
  { id: 0, tech: "React", icon: "🚀" },
  { id: 1, tech: "JavaScript (ES6+)", icon: "🔥" },
  { id: 2, tech: "HTML", icon: "📄" },
  { id: 3, tech: "CSS", icon: "🎨" },
  { id: 4, tech: "Node.js", icon: "🚀" },
  { id: 5, tech: "npm (Node Package Manager)", icon: "📦" },
  { id: 6, tech: "Git", icon: "🐙" },
  { id: 7, tech: "JSX (JavaScript XML)", icon: "✨" },
  { id: 8, tech: "Webpack", icon: "⚙️" },
  { id: 9, tech: "Babel", icon: "🔗" },
  { id: 10, tech: "RESTful APIs", icon: "🌐" },
  { id: 11, tech: "React Router", icon: "🔄" },
  { id: 12, tech: "State management", icon: "🔄" },
  { id: 13, tech: "Hooks", icon: "🎣" },
  { id: 14, tech: "Component lifecycle", icon: "⚙️" },
  { id: 15, tech: "Responsive design", icon: "📱" },
  { id: 16, tech: "Version control systems", icon: "🐙" },
  { id: 17, tech: "Code editors", icon: "💻" },
  { id: 18, tech: "Testing libraries", icon: "🧪" },
  { id: 19, tech: "Debugging tools", icon: "🔍" },
  { id: 20, tech: "Web development tools", icon: "🔧" },
  { id: 21, tech: "Package managers", icon: "📦" },
  { id: 22, tech: "AJAX", icon: "🌐" },
  { id: 23, tech: "Promises and async/await", icon: "⌛" },
  {
    id: 24,
    tech: "Basic understanding of browser rendering behavior",
    icon: "🌐",
  },
  { id: 25, tech: "Cross-browser compatibility", icon: "🌐" },
  { id: 26, tech: "Basic knowledge of GraphQL", icon: "🔄" },
  { id: 27, tech: "Server-side rendering", icon: "🔄" },
  { id: 28, tech: "CI/CD", icon: "🔄" },
];
